[package]
name = "flutter-engine"
description = "Flutter engine embedder in rust"
version = "0.2.1"
authors = ["juju <gliheng@foxmail.com>"]
keywords = ["flutter", "GUI"]
license = "MIT"
repository = "https://github.com/gliheng/flutter-rs"
readme = "crates-io.md"

[dependencies]
flutter-engine-sys = { path = "../flutter-engine-sys" }
glfw = "0.25.0"
gl = "0.11.0"
tokio = "0.1.13"
futures = "0.1.25"
tinyfiledialogs = "3.3.5"
libc = "0.2.44"
lazy_static = "1.2.0"
serde = "1.0.81"
serde_derive = "1.0.81"
serde_json = "1.0.33"
log = "0.4.6"

