[package]
name = "flutter-engine"
description = "Flutter engine embedder in rust"
version = "0.3.0"
authors = ["juju <gliheng@gmail.com>", "Sophie Tauchert <sophie@999eagle.moe>"]
keywords = ["flutter", "GUI"]
license = "MIT"
repository = "https://github.com/gliheng/flutter-rs"
readme = "crates-io.md"
edition = "2018"

[dependencies]
flutter-engine-sys = { path = "../flutter-engine-sys" }
glfw = "^0.28"
gl = "0.11.0"
libc = "0.2.44"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = "^0.4"
tokio = "^0.1.19"
lazy_static = "1.3.0"