[package]
name = "flutter-tools"
version = "0.1.0"
authors = ["Chandler Newman <chandler2newman@hotmail.co.uk>"]
edition = "2018"

[dependencies]
which = "3.1.1"
dirs = "2.0.2"
curl = "0.4.29"
indicatif = "0.14.0"
zip = "0.5.5"