[package]
name = "flutter-app-demo"
description = "Amazing desktop flutter app"
version = "0.2.0"
authors = ["juju <gliheng@foxmail.com>"]
publish = false
edition = "2018"

[package.metadata.flutter]
version = "3757390fa4b00d2d261bfdf5182d2e87c9113ff9"
identifier = "one.juju.flutter-app" # This is only used on mac

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
tokio = "0.1.13"
futures = "0.1.25"
tokio-timer = "0.2.8"
stream-cancel = "0.4.4"
flutter-engine = { path = "../../flutter-engine" }

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.6.3"

[build-dependencies]
flutter-download = { path = "../../flutter-download" }
cargo_toml = "0.4.0"
serde = "1.0.81"
serde_derive = "1.0.81"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1.9"
