[package]
name = "flutter-glfw"
description = "Flutter engine embedder in rust"
version = "0.3.5"
authors = ["juju <gliheng@gmail.com>", "Sophie Tauchert <sophie@999eagle.moe>"]
keywords = ["flutter", "GUI"]
license = "MIT"
repository = "https://github.com/gliheng/flutter-rs"
edition = "2018"

[dependencies]
async-std = "1.2"
flutter-engine-sys = { version = "0.3.5", path = "../flutter-engine-sys" }
flutter-engine = { version = "0.3.5", path = "../flutter-engine" }
flutter-plugins = { version = "0.3.5", path = "../flutter-plugins" }
futures-task = "0.3.1"
glfw = "^0.28"
gl = "0.11.0"
log = "^0.4"
lazy_static = "1.3.0"
locale_config = "^0.2"
parking_lot = "^0.10.0"
